config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]
  resources :players, only: [:index, :show, :create, :new] do
    scope module: :players do
      resources :clubs, only: [:index]
      resources :games, only: [:index]
      resources :ratings, only: [:index]
      resources :tournaments, only: [:index]
    end
  end
  resources :games, only: [:index, :new, :create, :show, :destroy]
  resources :matchups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :tournaments, only: [:index, :new, :update, :create] do
    scope module: :tournaments do
      resources :entries, only: [:index, :create, :destroy]
    end
  end
  post 'tournaments/:id/close_registration', to: 'tournaments#close_registration', as: :close_registration
  resources :round_robins, only: [:show]
  resources :single_eliminations, only: [:show]
  resources :clubs, only: [:new, :create, :index] do
    scope module: :clubs do
      resources :memberships, only: [:index, :new, :create]
    end
  end
  resources :clubs, only: :show, param: :slug
  resources :player_stats, only: [:show, :index]
  get '/player-vs-player', to: 'player_stats#player_vs_player'

  root 'players#index'
end

app/views/admin/index.html.haml
.row
  .small-6.columns
    .section
      %h3.sectionHeader
        Match Games
      .sectionBody
        %p
        %p
          = Game.played_on(Date.current).where.not(matchup_id: nil).count
  .small-6.columns
    .section
      %h3.sectionHeader
        Non-Match Games
      .sectionBody
        %p
          = Game.played_on(Date.current).where(matchup_id: nil).count
.row
  .small-6.columns
    .section
      %h3.sectionHeader
        Last Game
      .sectionBody
        = link_to "#{Game.last.winner.name} vs #{Game.last.loser.name}", game_path(Game.last)
  .small-6.columns
    .section
      %h3.sectionHeader
        Last Match
      .sectionBody
        = link_to "#{Matchup.last.primary.name} vs #{Matchup.last.secondary.name}", matchup_path(Matchup.last)
.row
  .small-6.columns
    .section
      %h3.sectionHeader
        Game Count
      .sectionBody
        %p
          = Game.count
  .small-6.columns
    .section
      %h3.sectionHeader
        Match Count
      .sectionBody
        %p
          = Matchup.count
.row
  .small-6.columns
    .section
      %h3.sectionHeader
        Player Total
      .sectionBody
        %p
          = Player.count
  .small-6.columns
    .section
      %h3.sectionHeader
        Matches Today
      .sectionBody
        %p
          = Matchup.where(created_at: Date.current.beginning_of_day..Date.current.end_of_day).count