config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]
  resources :players, only: [:index, :show, :create, :new] do
    scope module: :players do
      resources :clubs, only: [:index]
      resources :games, only: [:index]
      resources :ratings, only: [:index]
      resources :tournaments, only: [:index]
    end
  end
  resources :games, only: [:index, :new, :create, :show, :destroy]
  resources :matchups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :tournaments, only: [:index, :new, :update, :create] do
    scope module: :tournaments do
      resources :entries, only: [:index, :create, :destroy]
    end
  end
  post 'tournaments/:id/close_registration', to: 'tournaments#close_registration', as: :close_registration
  resources :round_robins, only: [:show]
  resources :single_eliminations, only: [:show]
  resources :clubs, only: [:new, :create, :index] do
    scope module: :clubs do
      resources :memberships, only: [:index, :new, :create]
    end
  end
  resources :clubs, only: :show, param: :slug
  resources :player_stats, only: [:show, :index]
  get '/player-vs-player', to: 'player_stats#player_vs_player'

  root 'players#index'
end

app/models/matchup.rb
# == Schema Information
#
# Table name: matchups
#
#  id            :integer          not null, primary key
#  primary_id    :integer
#  secondary_id  :integer
#  winner_id     :integer
#  tournament_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  series_max    :integer
#
# Indexes
#
#  index_matchups_on_tournament_id  (tournament_id)
#

class Matchup < ApplicationRecord
  belongs_to :tournament, optional: true
  belongs_to :winner, class_name: 'Player', optional: true
  belongs_to :primary, class_name: 'Player', optional: true
  belongs_to :secondary, class_name: 'Player', optional: true
  has_many :games

  def self.for_players(*players)
    where(primary_id: players, secondary_id: players).first
  end

  def ready?
    (primary && secondary) && !winner
  end

  def bracket_matchup
    Bracket.find_by matchup_id: id
  end

  def can_undo?
    games.include? Game.last
  end

  def add_game_results(game_results)
    return false if game_results.nil?
    MatchupCreator.new(matchup_id: id, game_results: game_results).save
  end

  def opponent_of(challenger)
    challenger == primary ? secondary : primary
  end

  def players
    [primary, secondary]
  end
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  def new
    @matchup = Matchup.new(primary_id: primary_id,
                           secondary_id: secondary_id,
                           series_max: 5)
  end

  def create
    @matchup = Matchup.create(primary_id: primary_id,
                              secondary_id: secondary_id,
                              series_max: series_max)
    if @matchup.add_game_results(games_params)
      redirect_to @matchup
    else
      flash.now[:alert] = 'Matches failed to create'
      render :edit
    end
  end

  def show
    @matchup = Matchup.find(params[:id])
  end

  def edit
    @matchup = Matchup.find(params[:id])
    if @matchup.winner
      redirect_to matchup_path(@matchup)
    end
  end

  def update
    @matchup = Matchup.find(params[:id])
    if @matchup.add_game_results(games_params)
      redirect_to @matchup
    else
      flash.now[:alert] = 'Matches failed to create'
      render :edit
    end
  end

  def destroy
    @matchup = Matchup.find(params[:id])
    @matchup.update winner_id: nil
    @matchup.games.most_recent.each do |game|
      GameDestroyer.new(game).undo_game!
    end
    redirect_to edit_matchup_path, notice: 'Match Destroyed'
  end

  private

  def games_params
    params.require(:games).permit!.to_h
  end

  def series_max
    params[:series_max]
  end

  def primary_id
    params[:primary_id]
  end

  def secondary_id
    params[:secondary_id]
  end

  def different_players
    secondary_id != primary_id
  end
end

app/views/matchups/_matchup_form.html.haml
= form_for(matchup) do |f|
  = hidden_field_tag :primary_id, matchup.primary_id
  = hidden_field_tag :secondary_id, matchup.secondary_id
  = hidden_field_tag :series_max, matchup.series_max
  - 1.upto(matchup.series_max) do |game_number|
    .row
      .small-1.columns
        %p
          = game_number
      .small-5.columns
        = radio_button("games", game_number, matchup.primary_id)
        = label_tag "games_#{game_number}_#{matchup.primary_id}", matchup.primary.name, {class: 'button secondary expanded', id: "label_games_#{game_number}_#{matchup.primary_id}"}
      .small-6.columns
        = radio_button("games", game_number, matchup.secondary_id)
        = label_tag "games_#{game_number}_#{matchup.secondary_id}", matchup.secondary.name, {class: 'button secondary expanded', id: "label_games_#{game_number}_#{matchup.secondary_id}"}
  %br
    .row
      .small-12.large-12.columns
        = submit_tag 'Submit', class: 'button expanded'

app/views/matchups/edit.html.haml
.row
  .small-12.large-12.columns
    %h3.text-center
      - if @matchup.tournament
        = @matchup.tournament.name
      - else
        = "#{@matchup.primary.name}(#{@matchup.primary.rating}) vs #{@matchup.secondary.name}(#{@matchup.secondary.rating})"
.row
  .small-12.large-12.columns
    %h4.text-center
      Please mark winner of each game in order. Best of #{@matchup.series_max}
.row
  .small-12.large-12.columns
    = render 'matchup_form', matchup: @matchup

app/views/matchups/new.html.haml
.row
  .small-12.columns
    %h3.text-center
      = "#{@matchup.primary.name}(#{@matchup.primary.rating}) vs #{@matchup.secondary.name}(#{@matchup.secondary.rating})"
    %h4.text-center
      Please mark winner of each game in order. Best of 5
.row
  .small-12.large-12.columns
    = render 'matchup_form', matchup: @matchup

app/views/matchups/show.html.haml
.row
  .small-12.large-12.columns
    %table{width: '100%'}
      %caption.gameDetails.text-center
        = "#{@matchup.winner.name} won!"
        %p
          #{@matchup.primary.name}'s new rating is #{@matchup.primary.rating}
        %p
          #{@matchup.secondary.name}'s new rating is #{@matchup.secondary.rating}
      %thead
        %tr
          %th
            Game
          %th
            Humble Victor
          %th
            Graceful Defeated
      - @matchup.games.each_with_index do |game, index|
        %tr
          %td
            = index + 1
          %td
            = link_for game.winner
            = "(#{game.winner_rating})"
          %td
            = link_for game.loser
            = "(#{game.loser_rating})"
.row
  .small-6.large-6.columns
    - if @matchup.tournament
      %h3.text-center
        = link_to 'Back to Tournament',  @matchup.tournament,{class: 'button expanded'}
    - else
      %h3.text-center
        = link_to 'Rematch', new_matchup_path(primary_id: @matchup.primary_id, secondary_id: @matchup.secondary_id), class: 'button expanded'
  - if @matchup.can_undo?
    .small-6.large-6.columns
      %h3.text-center
        = link_to 'Undo Match', @matchup, method: :delete, class: 'alert button expanded'