config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]
  resources :players, only: [:index, :show, :create, :new] do
    scope module: :players do
      resources :clubs, only: [:index]
      resources :games, only: [:index]
      resources :ratings, only: [:index]
      resources :tournaments, only: [:index]
    end
  end
  resources :games, only: [:index, :new, :create, :show, :destroy]
  resources :matchups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :tournaments, only: [:index, :new, :update, :create] do
    scope module: :tournaments do
      resources :entries, only: [:index, :create, :destroy]
    end
  end
  post 'tournaments/:id/close_registration', to: 'tournaments#close_registration', as: :close_registration
  resources :round_robins, only: [:show]
  resources :single_eliminations, only: [:show]
  resources :clubs, only: [:new, :create, :index] do
    scope module: :clubs do
      resources :memberships, only: [:index, :new, :create]
    end
  end
  resources :clubs, only: :show, param: :slug
  resources :player_stats, only: [:show, :index]
  get '/player-vs-player', to: 'player_stats#player_vs_player'

  root 'players#index'
end

app/models/round_robin.rb
# == Schema Information
#
# Table name: tournaments
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#  end_date   :datetime
#  type       :string
#  series_max :integer
#
# Indexes
#
#  index_tournaments_on_type  (type)
#

class RoundRobin < Tournament
  def build_matchups!
    players.map(&:id).combination(2).each do |combo|
      matchups << Matchup.create(primary_id: combo.first,
                                 secondary_id: combo.second,
                                 series_max: series_max)
    end
  end

  def players_by_points
    players.sort { |x,y|  match_points_for(y) <=> match_points_for(x) }
  end

  def rank_for(player)
    (players_by_points.find_index(player) + 1).ordinalize
  end

  def add_player(player)
    players.each do |current_player|
      matchups << Matchup.create(primary_id: player.id, secondary_id: current_player.id)
    end
    players << player
  end
end

app/controllers/round_robins_controller.rb
class RoundRobinsController < ApplicationController
  def show
    @tournament = RoundRobin.find(params[:id])
    redirect_to tournament_entries_path(@tournament) unless @tournament.started?
  end
end

app/views/round_robins/_matchups_for_player.html.haml
%h4
  Tournament Results for
  = player.name
%table{width: '100%'}
  %thead
    %tr
      %th
        Match
      %th
        Winner
      %th
        1
      %th
        2
      %th
        3
      %th
        4
      %th
        5
  %tbody
    - tournament.matchups_for(player).each do |matchup|
      - if matchup.winner
        %tr
          %td
            = link_to "#{player.name} vs. #{matchup.opponent_of(player).name}", matchup
          %td
            = matchup.winner.name
          - matchup.games.each do |game|
            %td
              = game.winner == player ? '1' : '0'

app/views/round_robins/show.html.haml
.row
  .small-12.columns
    %table{width: '100%'}
      %caption
        = @tournament.name
        = "(#{@tournament.type.titleize})"
        Results
        .tournament-subcaption
          - if @tournament.expired?
            %p
              Tournament ended on
              = @tournament.end_date.strftime('%m/%d/%Y')
          - else
            %p
              Click name to see remaining matches
            %p
              Tournament runs until
              = @tournament.end_date.strftime('%m/%d/%Y')
      %thead
        %tr
          %th
            Player
          %th
            Rating
          %th
            Points
      %tbody
      - @tournament.players.each do |player|
        %tr
          %td
            = link_to player.name, player_path(player)
          %td
            = player.rating
          %td
            = @tournament.match_points_for player
.row
  .small-12.large-12.columns
    .add-overflow
      %table{ 'width' => '100%', 'border' => '1' }
        %caption
          = @tournament.name
          = "(#{@tournament.type.titleize})"
        %thead
          %tr
            %th
              Player
            - @tournament.players.each do |player|
              %th
                = player.name

        %tbody
          - @tournament.players.each_with_index do |primary, index|
            %tr
              %td
                = link_to primary.name, player_path(primary)
              - @tournament.players.each do |secondary|
                - if primary == secondary
                  %td.empty-table-data
                - else
                  %td.text-center
                    - matchup = @tournament.matchups.for_players(primary, secondary)
                    - if matchup && matchup.winner
                      = link_to "#{matchup.winner  == primary ? '1' : '0'}", matchup
                    - elsif @tournament.expired?
                      N.A.
                    - else
                      = link_to 'Play', edit_matchup_path(matchup)