config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]
  resources :players, only: [:index, :show, :create, :new] do
    scope module: :players do
      resources :clubs, only: [:index]
      resources :games, only: [:index]
      resources :ratings, only: [:index]
      resources :tournaments, only: [:index]
    end
  end
  resources :games, only: [:index, :new, :create, :show, :destroy]
  resources :matchups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :tournaments, only: [:index, :new, :update, :create] do
    scope module: :tournaments do
      resources :entries, only: [:index, :create, :destroy]
    end
  end
  post 'tournaments/:id/close_registration', to: 'tournaments#close_registration', as: :close_registration
  resources :round_robins, only: [:show]
  resources :single_eliminations, only: [:show]
  resources :clubs, only: [:new, :create, :index] do
    scope module: :clubs do
      resources :memberships, only: [:index, :new, :create]
    end
  end
  resources :clubs, only: :show, param: :slug
  resources :player_stats, only: [:show, :index]
  get '/player-vs-player', to: 'player_stats#player_vs_player'

  root 'players#index'
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  rating     :integer          default(0), not null
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_players_on_name    (name)
#  index_players_on_rating  (rating)
#

class Player < ApplicationRecord
  has_many :won_games, foreign_key: 'winner_id', class_name: 'Game'
  has_many :lost_games, foreign_key: 'loser_id', class_name: 'Game'
  has_many :entries
  has_many :tournaments, through: :entries

  has_many :memberships
  has_many :clubs, through: :memberships

  validates_presence_of :name, :rating
  validates_uniqueness_of :name

  scope :by_name, -> { order(:name) }

  def self.last_winner
    Game.last.winner
  end

  def self.last_loser
    Game.last.loser
  end

  def games
    Game.for_player(self.id).most_recent
  end

  def add_rating!(change_in_rating)
    update!(rating: rating + change_in_rating)
  end

  def subtract_rating!(change_in_rating)
    update!(rating: rating - change_in_rating)
  end
end

app/controllers/players/accounts_controller.rb
module Players
  class AccountsController < ApplicationController
    def new
      @player = Player.find(params[:player_id])
      @account = Account.new(@player)
    end
  end
end

app/controllers/players/clubs_controller.rb
module Players
  class ClubsController < ApplicationController

    def index
      @player = Player.find(params[:player_id])
      @clubs = @player.clubs
    end

  end
end

app/controllers/players/games_controller.rb
module Players
  class GamesController < ApplicationController

    def index
      @player = Player.find(params[:player_id])
      @games = @player.games.page(params[:games_page]).per(10)
    end

  end
end

app/controllers/players/ratings_controller.rb
module Players
  class RatingsController < ApplicationController

    def index
      @player = Player.find(params[:player_id])
    end

  end
end

app/controllers/players/tournaments_controller.rb
module Players
  class TournamentsController < ApplicationController

    def index
      @player = Player.find(params[:player_id])
      @tournaments = @player.tournaments.page(params[:tournaments_page]).per(10)
    end

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all.sort_by(&:rating).reverse
  end

  def show
    @player = Player.find(params[:id])
    @stats = PlayerStatistician.new(@player)
    @games = @player.games.page(params[:games_page]).per(10)
    @tournaments = @player.tournaments.page(params[:tournaments_page]).per(10)
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.rating = 1000

    if @player.save
      redirect_to root_path, notice: 'Player created'
    else
      flash.now[:alert] = 'Player failed to save'
      render :new
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :rating)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
  def link_for(player)
    link_to player.name, player
  end

  def player_and_opponent_link(player, opponent)
    games_played = Game.for_players(player, opponent)
    player_wins = games_played.where(winner_id: player.id).count
    loser_wins = games_played.where(winner_id: opponent.id).count
    percent = (player_wins.to_f / games_played.count.to_f).round(2) * 100.0
    link_title = "#{player.name} vs. #{opponent.name}"
    #link_to link_title, new_matchup_path(primary_id: player.id, secondary_id: opponent.id), class: ''
    link_to new_matchup_path(primary_id: player.id, secondary_id: opponent.id), class: 'button expanded rematchLink' do
      link = content_tag(:span, number_to_percentage(percent, precision: 0), class: 'float-left')
      link += content_tag(:span, link_title, class: 'center')
      link += content_tag(:span, "#{player_wins} / #{loser_wins}", class: 'float-right')
      link
    end
  end

  def top_ten_players
    Player.all.sort_by(&:rating).reverse.first(10)
  end

  def last_game
    Game.last
  end

  def winner_id
    last_game.winner_id || 1
  end

  def loser_id
    last_game.loser_id || 1
  end

  def all_players_exclude(players)
    Player.by_name - players
  end

end

app/views/players/_daily_games.html.haml
- stats.todays_opponents.each do |opponent|
  - games_won = stats.games_won_today_against(opponent).count
  - games_played = stats.games_played_today_against(opponent).count
  %p.no-margin
    %span
      = stats.player.name
    %span.float-right
      = opponent.name
  .progress{"aria-valuemax" => "#{games_played}", "aria-valuemin" => "0", "aria-valuenow" => "#{games_won}", "aria-valuetext" => "#{games_won}", :role => "progressbar", :tabindex => "0"}
    %span.progress-meter{:style => "width: #{games_won.to_f/games_played.to_f * 100}%"}
      - if games_won > 0
        %p.progress-meter-text
          = games_won
          of
          = games_played
      - else
        %p.progress-meter-text.with_padding
          = games_won
          of
          = games_played

app/views/players/_game_info.html.haml
%table{width: '100%'}
  %caption
    Games Played (#{@player.games.count})
  %thead
    %tr
      %th
        Humble Victor
      %th
        Graceful Defeated
      %th
        Date
  %tbody
    = render @games

= paginate @games, param_name: 'games_page'

app/views/players/_profile_topbar.html.haml
.profile-top-bar
  .row
    = link_to player_path(player) do
      .column.small-3.with-border.profile-home
        %p.profile-link-text
          Profile
    = link_to player_games_path(player) do
      .column.small-3.with-border.profile-games
        %p.profile-link-text
          Games
    - if player.clubs.empty?
      = link_to clubs_path do
        .column.small-3.with-border.profile-clubs
          %p.profile-link-text
            Join a Club
    - else
      = link_to player_clubs_path(player) do
        .column.small-3.with-border.profile-clubs
          %p.profile-link-text
            Clubs
    = link_to player_tournaments_path(player) do
      .column.small-3.with-border.profile-tournaments
        %p.profile-link-text
          Tournaments

:javascript
  var element;
  var page = window.location.pathname.split('/')[3] || window.location.pathname.split('/')[1]
  switch(page){
    case 'games':
      element = document.getElementsByClassName("profile-games")[0]
      break;
    case 'clubs':
      element = document.getElementsByClassName("profile-clubs")[0]
      break;
    case 'tournaments':
      element = document.getElementsByClassName("profile-tournaments")[0]
      break;
    case 'players':
      element = document.getElementsByClassName("profile-home")[0]
      break;
    default:
      // no-opp
  }
  if (element) { element.classList.add('shade-background') };

app/views/players/_rating_over_time.html.haml
%canvas#rating-over-time-graph{:width => '400', :height => '300', 'data-player-id' => @player.id}

app/views/players/index.html.haml
.player-index.float-center
  %table
    %thead
      %tr
        %th
          Rank
        %th
          Name
        %th
          Rating
        %th
          Won / Lost
    = render @players

app/views/players/new.html.haml
.row
  .small-12.large-6.columns
    %h3 Add Player

= form_for @player do |f|
  .row
    .small-12.large-6.columns
      = f.label :name do
        Name
        = f.text_field :name
  .row
    .small-12.large-6.columns
      = f.submit 'Add Player', class: 'button expanded'

app/views/players/show.html.haml
= render partial: 'players/profile_topbar', locals: { player: @player }
.row.profile-circles
  .column.small-12
    .circle.big-circle.float-center
      %p.center-of-circle-big
        = @player.rating
    %p.text-center.player-name
      = @player.name

.row
  .column.small-3
    .circle.little-circle.float-center
      %p.center-of-circle-little
        = @stats.average_rating
    %p.text-center Average
  .column.small-3
    .circle.little-circle.float-center
      %p.center-of-circle-little
        = @stats.highest_rating_achieved
    %p.text-center High
  .column.small-3
    .circle.little-circle.float-center.daily-rating-change
      %p.text-center.center-of-circle-little
        = @stats.daily_rating_change
    %p.text-center Today
  .column.small-3
    .circle.little-circle.float-center
      %p.center-of-circle-little
        = number_to_percentage @stats.win_percentage, precision: 0
    %p.text-center Win Rate

- if @stats.todays_games.count > 0
  .row
    .column.small-12
      %ul.accordion{"data-accordion" => "", "data-slide-speed" => '0', "data-allow-all-closed" => "true"}
        %li.accordion-item.is-active{"data-accordion-item" => ""}
          %a.accordion-title{:href => "#"}
            Today's wins
            = @stats.games_won_today.count
            of
            = @stats.todays_games.count
          .accordion-content{"data-tab-content" => ""}
            = render 'daily_games', stats: @stats
        %li.accordion-item{"data-accordion-item" => ""}
          %a.accordion-title{:href => "#"} Rating Over Time
          .accordion-content{"data-tab-content" => ""}
            = link_to player_ratings_path(@player) do
              .rating-over-time
                %canvas#rating-over-time-graph{'data-player-id' => @player.id, 'data-limit' => 10 }
- else
  = link_to player_ratings_path(@player) do
    .rating-over-time
      %canvas#rating-over-time-graph{'data-player-id' => @player.id, 'data-limit' => 10 }

.row
  .rematchHeaders
    .column.small-10
      %p
        %strong
          Play a Rematch
    .column.small-2
      %p.text-center
        %strong
          Stats

- @stats.opponents_by_games_played.each do |opp|
  .row
    .column.small-10
      = player_and_opponent_link(@player, opp)
    .column.small-2
      = link_to player_stats_path(primary: @player, secondary: opp) do
        %i.fas.fa-chart-bar.fa-sm.button.expanded

:javascript
  $('.accordion').foundation()